import Day8.parse
import Day8.run1
import Day8.run2
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test

class Day8Test {
    val sample = """
        ............
        ........0...
        .....0......
        .......0....
        ....0.......
        ......A.....
        ............
        ............
        ........A...
        .........A..
        ............
        ............
    """.trimIndent()
    val input = parse(sample)
    @Test
    fun test1() {
        assertEquals(14, run1(input))
    }
    @Test
    fun test2() {
        assertEquals(34, run2(input))
    }

}